const products = [
  {
    id: "9780345391803",
    name: "Jurassic Park",
    author: "Michael Crichton",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Jurassic Park is a thrilling science fiction novel that explores the disastrous consequences of recreating dinosaurs through genetic engineering. Set on a remote island, a group of scientists and visitors find themselves facing terrifying and deadly dinosaurs, leading to a fight for survival.",
    price: 9.99,
    format: "Paperback",
    genre: ["Science Fiction", "Thriller"],
    pages: 464,
    publisher: "Ballantine Books",
    language: "English",
    rating: 4.3,
    isInStock: true,
  },
  {
    id: "9780061120084",
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "To Kill a Mockingbird is a classic novel set in the 1930s Southern United States. It addresses themes of racial injustice and moral growth through the eyes of young Scout Finch. The story revolves around Scout's father, Atticus Finch, a lawyer who defends an African American man accused of raping a white woman.",
    price: 12.99,
    format: "Hardcover",
    genre: ["Classic", "Fiction"],
    pages: 336,
    publisher: "HarperCollins",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9780590353427",
    name: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Harry Potter and the Sorcerer's Stone is the first book in the beloved Harry Potter series. It introduces the young wizard Harry Potter as he discovers his magical heritage and embarks on a thrilling adventure at Hogwarts School of Witchcraft and Wizardry.",
    price: 8.99,
    format: "Paperback",
    genre: ["Fantasy", "Young Adult"],
    pages: 336,
    publisher: "Scholastic",
    language: "English",
    rating: 4.7,
    isInStock: true,
  },
  {
    id: "9780062316097",
    name: "The Nightingale",
    author: "Kristin Hannah",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Nightingale is a historical fiction novel set in France during World War II. It follows the lives of two sisters, Vianne and Isabelle, as they navigate the challenges and horrors of war, resistance, and the strength of family bonds.",
    price: 10.49,
    format: "Paperback",
    genre: ["Historical Fiction", "War"],
    pages: 608,
    publisher: "St. Martin's Press",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780735219090",
    name: "Becoming",
    author: "Michelle Obama",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Becoming is a captivating memoir by Michelle Obama, the former First Lady of the United States. In this deeply personal book, Michelle Obama shares her journey from her childhood in Chicago to her experiences in the White House, inspiring readers with her strength, grace, and resilience.",
    price: 17.99,
    format: "Hardcover",
    genre: ["Biography", "Memoir"],
    pages: 448,
    publisher: "Crown Publishing Group",
    language: "English",
    rating: 4.9,
    isInStock: true,
  },
  {
    id: "9780062564047",
    name: "Circe",
    author: "Madeline Miller",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Circe is a captivating retelling of Greek mythology, centered around the life of the witch-goddess Circe. It explores her journey of self-discovery, love, and power as she interacts with famous mythological figures such as Odysseus, Athena, and the Minotaur.",
    price: 16.99,
    format: "Paperback",
    genre: ["Fantasy", "Mythology"],
    pages: 400,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781501175466",
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Where the Crawdads Sing is a mesmerizing mystery novel set in the marshes of North Carolina. It follows the story of Kya Clark, known as the 'Marsh Girl,' as she navigates loneliness, love, and a haunting murder investigation.",
    price: 11.99,
    format: "Paperback",
    genre: ["Mystery", "Fiction"],
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781451673319",
    name: "Unbroken",
    author: "Laura Hillenbrand",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Unbroken is a gripping biography of Louis Zamperini, an Olympic athlete and World War II prisoner of war. The book details his resilience, survival, and triumph over unimaginable adversity.",
    price: 12.49,
    format: "Paperback",
    genre: ["Biography", "History"],
    pages: 528,
    publisher: "Random House",
    language: "English",
    rating: 4.7,
    isInStock: true,
  },
  {
    id: "9780735210738",
    name: "The Underground Railroad",
    author: "Colson Whitehead",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Underground Railroad is a powerful historical fiction novel that reimagines the Underground Railroad as a literal network of underground tracks. It follows the journey of Cora, a slave escaping from a Georgia plantation, as she seeks freedom and encounters various challenges along the way.",
    price: 10.99,
    format: "Paperback",
    genre: ["Historical Fiction", "Literary Fiction"],
    pages: 400,
    publisher: "Doubleday",
    language: "English",
    rating: 4.4,
    isInStock: true,
  },
  {
    id: "9780061122415",
    name: "The Alchemist",
    author: "Paulo Coelho",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Alchemist is a timeless philosophical novel that follows the journey of Santiago, an Andalusian shepherd boy, as he searches for a hidden treasure. Along the way, he encounters life-changing lessons and learns about the true meaning of life and destiny.",
    price: 9.29,
    format: "Paperback",
    genre: ["Fiction", "Philosophy"],
    pages: 208,
    publisher: "HarperOne",
    language: "English",
    rating: 4.7,
    isInStock: true,
  },
  {
    id: "9780743273565",
    name: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "A Thousand Splendid Suns is a heart-wrenching and powerful novel set in Afghanistan. It tells the intertwined stories of two women, Mariam and Laila, as they endure hardships and find strength in their friendship during the tumultuous years of war and oppression.",
    price: 13.49,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 432,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780062316110",
    name: "The Goldfinch",
    author: "Donna Tartt",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Goldfinch is a compelling coming-of-age novel that follows the life of Theodore Decker, who survives a tragic event that alters the course of his life. It explores themes of loss, redemption, and the power of art.",
    price: 14.49,
    format: "Paperback",
    genre: ["Fiction", "Literary Fiction"],
    pages: 784,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9780385514231",
    name: "The Da Vinci Code",
    author: "Dan Brown",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Da Vinci Code is a thrilling mystery novel that revolves around the quest to uncover hidden secrets and symbols hidden in artworks. It follows the adventures of symbologist Robert Langdon as he investigates a murder that leads to a deeper and centuries-old conspiracy.",
    price: 8.99,
    format: "Paperback",
    genre: ["Mystery", "Thriller"],
    pages: 624,
    publisher: "Anchor Books",
    language: "English",
    rating: 4.3,
    isInStock: true,
  },
  {
    id: "9780553382563",
    name: "A Game of Thrones",
    author: "George R.R. Martin",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "A Game of Thrones is the first book in the epic fantasy series 'A Song of Ice and Fire.' It introduces readers to the world of Westeros, where noble houses vie for power, and a dark threat looms beyond the Wall in the North.",
    price: 9.99,
    format: "Paperback",
    genre: ["Fantasy", "Epic"],
    pages: 848,
    publisher: "Bantam Books",
    language: "English",
    rating: 4.4,
    isInStock: true,
  },
  {
    id: "9780374533557",
    name: "Bad Feminist",
    author: "Roxane Gay",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Bad Feminist is a collection of essays that explore feminism, pop culture, politics, and personal experiences. Roxane Gay offers thought-provoking insights and critiques while challenging conventional notions of feminism.",
    price: 11.99,
    format: "Paperback",
    genre: ["Non-Fiction", "Feminism"],
    pages: 336,
    publisher: "Harper Perennial",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9780812984965",
    name: "The Book Thief",
    author: "Markus Zusak",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Book Thief is a beautifully written historical fiction novel set in Nazi Germany. It follows the life of Liesel Meminger, who finds solace in books during the war, leading to a touching tale of friendship, love, and the power of words.",
    price: 10.99,
    format: "Paperback",
    genre: ["Historical Fiction", "Young Adult"],
    pages: 592,
    publisher: "Knopf Books for Young Readers",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780062124265",
    name: "The Martian",
    author: "Andy Weir",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Martian is a gripping science fiction novel that follows astronaut Mark Watney's struggle for survival on Mars after being stranded by his crew. The book combines humor, science, and suspense to create an engaging and realistic tale of survival.",
    price: 8.99,
    format: "Paperback",
    genre: ["Science Fiction", "Adventure"],
    pages: 400,
    publisher: "Broadway Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781400079094",
    name: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Shadow of the Wind is a captivating historical fiction novel set in post-war Barcelona. It follows the story of young Daniel Sempere as he discovers an enigmatic book by a mysterious author, leading to a thrilling journey of secrets, love, and intrigue.",
    price: 14.49,
    format: "Paperback",
    genre: ["Historical Fiction", "Mystery"],
    pages: 487,
    publisher: "Penguin Books",
    language: "English",
    rating: 4.3,
    isInStock: true,
  },
  {
    id: "9780385537858",
    name: "The Night Circus",
    author: "Erin Morgenstern",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Night Circus is an enchanting fantasy novel that revolves around the magical and mysterious Le Cirque des Rêves (The Night Circus). As two young magicians engage in a high-stakes competition, their lives become entwined in a beautiful and imaginative world.",
    price: 12.99,
    format: "Paperback",
    genre: ["Fantasy", "Romance"],
    pages: 512,
    publisher: "Anchor",
    language: "English",
    rating: 4.4,
    isInStock: true,
  },
  {
    id: "9781451673289",
    name: "All the Light We Cannot See",
    author: "Anthony Doerr",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "All the Light We Cannot See is a beautifully written historical fiction novel set during World War II. It weaves together the lives of Marie-Laure, a blind French girl, and Werner, a German soldier, as their paths cross amidst the ravages of war.",
    price: 10.49,
    format: "Paperback",
    genre: ["Historical Fiction", "War"],
    pages: 544,
    publisher: "Scribner",
    language: "English",
    rating: 4.5,
    isInStock: true,
  },
  {
    id: "9781400034770",
    name: "The Road",
    author: "Cormac McCarthy",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Road is a haunting post-apocalyptic novel that follows a father and son as they journey through a desolate and dangerous landscape. Their struggle for survival amidst hopelessness explores themes of love, loss, and the human spirit.",
    price: 11.99,
    format: "Paperback",
    genre: ["Fiction", "Dystopian"],
    pages: 304,
    publisher: "Vintage",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780735219090",
    name: "Becoming",
    author: "Michelle Obama",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Becoming is a captivating memoir by Michelle Obama, the former First Lady of the United States. In this deeply personal book, Michelle Obama shares her journey from her childhood in Chicago to her experiences in the White House, inspiring readers with her strength, grace, and resilience.",
    price: 17.99,
    format: "Hardcover",
    genre: ["Biography", "Memoir"],
    pages: 448,
    publisher: "Crown Publishing Group",
    language: "English",
    rating: 4.9,
    isInStock: true,
  },
  {
    id: "9780062564047",
    name: "Circe",
    author: "Madeline Miller",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Circe is a captivating retelling of Greek mythology, centered around the life of the witch-goddess Circe. It explores her journey of self-discovery, love, and power as she interacts with famous mythological figures such as Odysseus, Athena, and the Minotaur.",
    price: 16.99,
    format: "Paperback",
    genre: ["Fantasy", "Mythology"],
    pages: 400,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781501175466",
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Where the Crawdads Sing is a mesmerizing mystery novel set in the marshes of North Carolina. It follows the story of Kya Clark, known as the 'Marsh Girl,' as she navigates loneliness, love, and a haunting murder investigation.",
    price: 11.99,
    format: "Paperback",
    genre: ["Mystery", "Fiction"],
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781451673319",
    name: "Unbroken",
    author: "Laura Hillenbrand",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Unbroken is a gripping biography of Louis Zamperini, an Olympic athlete and World War II prisoner of war. The book details his resilience, survival, and triumph over unimaginable adversity.",
    price: 12.49,
    format: "Paperback",
    genre: ["Biography", "History"],
    pages: 528,
    publisher: "Random House",
    language: "English",
    rating: 4.7,
    isInStock: true,
  },
  {
    id: "9780735210738",
    name: "The Underground Railroad",
    author: "Colson Whitehead",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Underground Railroad is a powerful historical fiction novel that reimagines the Underground Railroad as a literal network of underground tracks. It follows the journey of Cora, a slave escaping from a Georgia plantation, as she seeks freedom and encounters various challenges along the way.",
    price: 10.99,
    format: "Paperback",
    genre: ["Historical Fiction", "Literary Fiction"],
    pages: 400,
    publisher: "Doubleday",
    language: "English",
    rating: 4.4,
    isInStock: true,
  },
  {
    id: "9780061122415",
    name: "The Alchemist",
    author: "Paulo Coelho",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Alchemist is a timeless philosophical novel that follows the journey of Santiago, an Andalusian shepherd boy, as he searches for a hidden treasure. Along the way, he encounters life-changing lessons and learns about the true meaning of life and destiny.",
    price: 9.29,
    format: "Paperback",
    genre: ["Fiction", "Philosophy"],
    pages: 208,
    publisher: "HarperOne",
    language: "English",
    rating: 4.7,
    isInStock: true,
  },
  {
    id: "9780743273565",
    name: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "A Thousand Splendid Suns is a heart-wrenching and powerful novel set in Afghanistan. It tells the intertwined stories of two women, Mariam and Laila, as they endure hardships and find strength in their friendship during the tumultuous years of war and oppression.",
    price: 13.49,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 432,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781400034770",
    name: "The Road",
    author: "Cormac McCarthy",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Road is a haunting post-apocalyptic novel that follows a father and son as they journey through a desolate and dangerous landscape. Their struggle for survival amidst hopelessness explores themes of love, loss, and the human spirit.",
    price: 11.99,
    format: "Paperback",
    genre: ["Fiction", "Dystopian"],
    pages: 304,
    publisher: "Vintage",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780735219090",
    name: "Becoming",
    author: "Michelle Obama",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Becoming is a captivating memoir by Michelle Obama, the former First Lady of the United States. In this deeply personal book, Michelle Obama shares her journey from her childhood in Chicago to her experiences in the White House, inspiring readers with her strength, grace, and resilience.",
    price: 17.99,
    format: "Hardcover",
    genre: ["Biography", "Memoir"],
    pages: 448,
    publisher: "Crown Publishing Group",
    language: "English",
    rating: 4.9,
    isInStock: true,
  },
  {
    id: "9780062564047",
    name: "Circe",
    author: "Madeline Miller",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Circe is a captivating retelling of Greek mythology, centered around the life of the witch-goddess Circe. It explores her journey of self-discovery, love, and power as she interacts with famous mythological figures such as Odysseus, Athena, and the Minotaur.",
    price: 16.99,
    format: "Paperback",
    genre: ["Fantasy", "Mythology"],
    pages: 400,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781501175466",
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Where the Crawdads Sing is a mesmerizing mystery novel set in the marshes of North Carolina. It follows the story of Kya Clark, known as the 'Marsh Girl,' as she navigates loneliness, love, and a haunting murder investigation.",
    price: 11.99,
    format: "Paperback",
    genre: ["Mystery", "Fiction"],
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781451673289",
    name: "All the Light We Cannot See",
    author: "Anthony Doerr",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "All the Light We Cannot See is a beautifully written historical fiction novel set during World War II. It weaves together the lives of Marie-Laure, a blind French girl, and Werner, a German soldier, as their paths cross amidst the ravages of war.",
    price: 10.49,
    format: "Paperback",
    genre: ["Historical Fiction", "War"],
    pages: 544,
    publisher: "Scribner",
    language: "English",
    rating: 4.5,
    isInStock: true,
  },
  {
    id: "9781400034770",
    name: "The Road",
    author: "Cormac McCarthy",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Road is a haunting post-apocalyptic novel that follows a father and son as they journey through a desolate and dangerous landscape. Their struggle for survival amidst hopelessness explores themes of love, loss, and the human spirit.",
    price: 11.99,
    format: "Paperback",
    genre: ["Fiction", "Dystopian"],
    pages: 304,
    publisher: "Vintage",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780735219090",
    name: "Becoming",
    author: "Michelle Obama",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Becoming is a captivating memoir by Michelle Obama, the former First Lady of the United States. In this deeply personal book, Michelle Obama shares her journey from her childhood in Chicago to her experiences in the White House, inspiring readers with her strength, grace, and resilience.",
    price: 17.99,
    format: "Hardcover",
    genre: ["Biography", "Memoir"],
    pages: 448,
    publisher: "Crown Publishing Group",
    language: "English",
    rating: 4.9,
    isInStock: true,
  },
  {
    id: "9780062564047",
    name: "Circe",
    author: "Madeline Miller",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Circe is a captivating retelling of Greek mythology, centered around the life of the witch-goddess Circe. It explores her journey of self-discovery, love, and power as she interacts with famous mythological figures such as Odysseus, Athena, and the Minotaur.",
    price: 16.99,
    format: "Paperback",
    genre: ["Fantasy", "Mythology"],
    pages: 400,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781501175466",
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Where the Crawdads Sing is a mesmerizing mystery novel set in the marshes of North Carolina. It follows the story of Kya Clark, known as the 'Marsh Girl,' as she navigates loneliness, love, and a haunting murder investigation.",
    price: 11.99,
    format: "Paperback",
    genre: ["Mystery", "Fiction"],
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781451673289",
    name: "All the Light We Cannot See",
    author: "Anthony Doerr",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "All the Light We Cannot See is a beautifully written historical fiction novel set during World War II. It weaves together the lives of Marie-Laure, a blind French girl, and Werner, a German soldier, as their paths cross amidst the ravages of war.",
    price: 10.49,
    format: "Paperback",
    genre: ["Historical Fiction", "War"],
    pages: 544,
    publisher: "Scribner",
    language: "English",
    rating: 4.5,
    isInStock: true,
  },
  {
    id: "9781400034770",
    name: "The Road",
    author: "Cormac McCarthy",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Road is a haunting post-apocalyptic novel that follows a father and son as they journey through a desolate and dangerous landscape. Their struggle for survival amidst hopelessness explores themes of love, loss, and the human spirit.",
    price: 11.99,
    format: "Paperback",
    genre: ["Fiction", "Dystopian"],
    pages: 304,
    publisher: "Vintage",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780735219090",
    name: "Becoming",
    author: "Michelle Obama",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Becoming is a captivating memoir by Michelle Obama, the former First Lady of the United States. In this deeply personal book, Michelle Obama shares her journey from her childhood in Chicago to her experiences in the White House, inspiring readers with her strength, grace, and resilience.",
    price: 17.99,
    format: "Hardcover",
    genre: ["Biography", "Memoir"],
    pages: 448,
    publisher: "Crown Publishing Group",
    language: "English",
    rating: 4.9,
    isInStock: true,
  },
  {
    id: "9780062564047",
    name: "Circe",
    author: "Madeline Miller",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Circe is a captivating retelling of Greek mythology, centered around the life of the witch-goddess Circe. It explores her journey of self-discovery, love, and power as she interacts with famous mythological figures such as Odysseus, Athena, and the Minotaur.",
    price: 16.99,
    format: "Paperback",
    genre: ["Fantasy", "Mythology"],
    pages: 400,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781501175466",
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Where the Crawdads Sing is a mesmerizing mystery novel set in the marshes of North Carolina. It follows the story of Kya Clark, known as the 'Marsh Girl,' as she navigates loneliness, love, and a haunting murder investigation.",
    price: 11.99,
    format: "Paperback",
    genre: ["Mystery", "Fiction"],
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781451673289",
    name: "All the Light We Cannot See",
    author: "Anthony Doerr",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "All the Light We Cannot See is a beautifully written historical fiction novel set during World War II. It weaves together the lives of Marie-Laure, a blind French girl, and Werner, a German soldier, as their paths cross amidst the ravages of war.",
    price: 10.49,
    format: "Paperback",
    genre: ["Historical Fiction", "War"],
    pages: 544,
    publisher: "Scribner",
    language: "English",
    rating: 4.5,
    isInStock: true,
  },
  {
    id: "9781400034770",
    name: "The Road",
    author: "Cormac McCarthy",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Road is a haunting post-apocalyptic novel that follows a father and son as they journey through a desolate and dangerous landscape. Their struggle for survival amidst hopelessness explores themes of love, loss, and the human spirit.",
    price: 11.99,
    format: "Paperback",
    genre: ["Fiction", "Dystopian"],
    pages: 304,
    publisher: "Vintage",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780735219090",
    name: "Becoming",
    author: "Michelle Obama",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Becoming is a captivating memoir by Michelle Obama, the former First Lady of the United States. In this deeply personal book, Michelle Obama shares her journey from her childhood in Chicago to her experiences in the White House, inspiring readers with her strength, grace, and resilience.",
    price: 17.99,
    format: "Hardcover",
    genre: ["Biography", "Memoir"],
    pages: 448,
    publisher: "Crown Publishing Group",
    language: "English",
    rating: 4.9,
    isInStock: true,
  },
  {
    id: "9780062564047",
    name: "Circe",
    author: "Madeline Miller",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Circe is a captivating retelling of Greek mythology, centered around the life of the witch-goddess Circe. It explores her journey of self-discovery, love, and power as she interacts with famous mythological figures such as Odysseus, Athena, and the Minotaur.",
    price: 16.99,
    format: "Paperback",
    genre: ["Fantasy", "Mythology"],
    pages: 400,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781501175466",
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Where the Crawdads Sing is a mesmerizing mystery novel set in the marshes of North Carolina. It follows the story of Kya Clark, known as the 'Marsh Girl,' as she navigates loneliness, love, and a haunting murder investigation.",
    price: 11.99,
    format: "Paperback",
    genre: ["Mystery", "Fiction"],
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781451673289",
    name: "All the Light We Cannot See",
    author: "Anthony Doerr",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "All the Light We Cannot See is a beautifully written historical fiction novel set during World War II. It weaves together the lives of Marie-Laure, a blind French girl, and Werner, a German soldier, as their paths cross amidst the ravages of war.",
    price: 10.49,
    format: "Paperback",
    genre: ["Historical Fiction", "War"],
    pages: 544,
    publisher: "Scribner",
    language: "English",
    rating: 4.5,
    isInStock: true,
  },
  {
    id: "9781400034770",
    name: "The Road",
    author: "Cormac McCarthy",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Road is a haunting post-apocalyptic novel that follows a father and son as they journey through a desolate and dangerous landscape. Their struggle for survival amidst hopelessness explores themes of love, loss, and the human spirit.",
    price: 11.99,
    format: "Paperback",
    genre: ["Fiction", "Dystopian"],
    pages: 304,
    publisher: "Vintage",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780735219090",
    name: "Becoming",
    author: "Michelle Obama",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Becoming is a captivating memoir by Michelle Obama, the former First Lady of the United States. In this deeply personal book, Michelle Obama shares her journey from her childhood in Chicago to her experiences in the White House, inspiring readers with her strength, grace, and resilience.",
    price: 17.99,
    format: "Hardcover",
    genre: ["Biography", "Memoir"],
    pages: 448,
    publisher: "Crown Publishing Group",
    language: "English",
    rating: 4.9,
    isInStock: true,
  },
  {
    id: "9780062564047",
    name: "Circe",
    author: "Madeline Miller",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Circe is a captivating retelling of Greek mythology, centered around the life of the witch-goddess Circe. It explores her journey of self-discovery, love, and power as she interacts with famous mythological figures such as Odysseus, Athena, and the Minotaur.",
    price: 16.99,
    format: "Paperback",
    genre: ["Fantasy", "Mythology"],
    pages: 400,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781501175466",
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Where the Crawdads Sing is a mesmerizing mystery novel set in the marshes of North Carolina. It follows the story of Kya Clark, known as the 'Marsh Girl,' as she navigates loneliness, love, and a haunting murder investigation.",
    price: 11.99,
    format: "Paperback",
    genre: ["Mystery", "Fiction"],
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781451673289",
    name: "All the Light We Cannot See",
    author: "Anthony Doerr",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "All the Light We Cannot See is a beautifully written historical fiction novel set during World War II. It weaves together the lives of Marie-Laure, a blind French girl, and Werner, a German soldier, as their paths cross amidst the ravages of war.",
    price: 10.49,
    format: "Paperback",
    genre: ["Historical Fiction", "War"],
    pages: 544,
    publisher: "Scribner",
    language: "English",
    rating: 4.5,
    isInStock: true,
  },
  {
    id: "9781400034770",
    name: "The Road",
    author: "Cormac McCarthy",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Road is a haunting post-apocalyptic novel that follows a father and son as they journey through a desolate and dangerous landscape. Their struggle for survival amidst hopelessness explores themes of love, loss, and the human spirit.",
    price: 11.99,
    format: "Paperback",
    genre: ["Fiction", "Dystopian"],
    pages: 304,
    publisher: "Vintage",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9780735219090",
    name: "Becoming",
    author: "Michelle Obama",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Becoming is a captivating memoir by Michelle Obama, the former First Lady of the United States. In this deeply personal book, Michelle Obama shares her journey from her childhood in Chicago to her experiences in the White House, inspiring readers with her strength, grace, and resilience.",
    price: 17.99,
    format: "Hardcover",
    genre: ["Biography", "Memoir"],
    pages: 448,
    publisher: "Crown Publishing Group",
    language: "English",
    rating: 4.9,
    isInStock: true,
  },
  {
    id: "9780062564047",
    name: "Circe",
    author: "Madeline Miller",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Circe is a captivating retelling of Greek mythology, centered around the life of the witch-goddess Circe. It explores her journey of self-discovery, love, and power as she interacts with famous mythological figures such as Odysseus, Athena, and the Minotaur.",
    price: 16.99,
    format: "Paperback",
    genre: ["Fantasy", "Mythology"],
    pages: 400,
    publisher: "Back Bay Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
  {
    id: "9781501175466",
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "Where the Crawdads Sing is a mesmerizing mystery novel set in the marshes of North Carolina. It follows the story of Kya Clark, known as the 'Marsh Girl,' as she navigates loneliness, love, and a haunting murder investigation.",
    price: 11.99,
    format: "Paperback",
    genre: ["Mystery", "Fiction"],
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
    rating: 4.8,
    isInStock: true,
  },
  {
    id: "9781451673289",
    name: "All the Light We Cannot See",
    author: "Anthony Doerr",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "All the Light We Cannot See is a beautifully written historical fiction novel set during World War II. It weaves together the lives of Marie-Laure, a blind French girl, and Werner, a German soldier, as their paths cross amidst the ravages of war.",
    price: 10.49,
    format: "Paperback",
    genre: ["Historical Fiction", "War"],
    pages: 544,
    publisher: "Scribner",
    language: "English",
    rating: 4.5,
    isInStock: true,
  },
  {
    id: "9781400034770",
    name: "The Road",
    author: "Cormac McCarthy",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Road is a haunting post-apocalyptic novel that follows a father and son as they journey through a desolate and dangerous landscape. Their struggle for survival amidst hopelessness explores themes of love, loss, and the human spirit.",
    price: 11.99,
    format: "Paperback",
    genre: ["Fiction", "Dystopian"],
    pages: 304,
    publisher: "Vintage",
    language: "English",
    rating: 4.1,
    isInStock: true,
  },
  {
    id: "9781400032493",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    coverImage:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193.jpg",
    description:
      "The Kite Runner is a powerful novel that explores themes of friendship, guilt, and redemption in war-torn Afghanistan. It tells the story of Amir and his journey to confront the haunting memories of his past and find a way to make amends.",
    price: 9.89,
    format: "Paperback",
    genre: ["Fiction", "Historical Fiction"],
    pages: 400,
    publisher: "Riverhead Books",
    language: "English",
    rating: 4.6,
    isInStock: true,
  },
];

module.exports = products;
